# Only use spaces to indent .yml configuration.
# -----
image: tbaltrushaitis/ubuntu-nodejs

pipelines:
  default:
    - step:
        script:
          - printf "\n\n\nHi! I am OS:\n$(uname -a)\n\n\n"
          - free -m
          - lscpu
          - whoami
          - id
          - getent passwd
          - df -H
          - date
          - ping 8.8.8.8 -c 4
          - node -v
          - npm -v
          - #git clone
          - printf "BITBUCKET_BRANCH \t = \t ${BITBUCKET_BRANCH}\n"
          - printf "BITBUCKET_CLONE_DIR \t = \t ${BITBUCKET_CLONE_DIR}\n"
          - printf "BITBUCKET_COMMIT \t = \t ${BITBUCKET_COMMIT}\n"
          - printf "BITBUCKET_REPO_OWNER \t = \t ${BITBUCKET_REPO_OWNER}\n"
          - printf "BITBUCKET_REPO_SLUG \t = \t ${BITBUCKET_REPO_SLUG}\n"
          - printf "BITBUCKET_TAG \t = \t ${BITBUCKET_TAG}\n"
