# This is a sample build configuration for all languages.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: docker-image:tag

image: tbaltrushaitis/ubuntu-nodejs

pipelines:
  default:
    - step:
        script:
          - printf "Hi from OS! I am:\n$(uname -a)"
          - node -v
          - npm -v
          - getent passwd
          - whoami
          - id
          - df -H
          - date
          - ping 8.8.8.8 -c 4
          - free -m
          - lscpu
          